#!/usr/bin/env node
/**
 * Verify a Dilithium5 signature generated by go-qrllib using qrypto.js.
 * Reads: /tmp/goqrllib_dilithium5_pk.bin, /tmp/goqrllib_dilithium5_sig.bin, /tmp/goqrllib_dilithium5_msg.bin
 */

import { readFileSync } from 'fs';
import { cryptoSignVerify } from '../../packages/dilithium5/src/sign.js';

console.log('=== qrypto.js Dilithium5 Signature Verification ===');

// Read go-qrllib generated files
const pk = readFileSync('/tmp/goqrllib_dilithium5_pk.bin');
const sig = readFileSync('/tmp/goqrllib_dilithium5_sig.bin');
const msg = readFileSync('/tmp/goqrllib_dilithium5_msg.bin');

console.log(`Public key size: ${pk.length} bytes`);
console.log(`Signature size: ${sig.length} bytes`);
console.log(`Message size: ${msg.length} bytes`);
console.log(`Message: "${msg.toString('utf8')}"`);
console.log(`Public key (first 32 bytes): ${pk.slice(0, 32).toString('hex')}`);
console.log(`Signature (first 32 bytes): ${sig.slice(0, 32).toString('hex')}`);

// Verify signature
const valid = cryptoSignVerify(sig, msg, pk);

if (valid) {
  console.log('\n✓ Signature verification PASSED');
  process.exit(0);
} else {
  console.error('\n✗ Signature verification FAILED');
  process.exit(1);
}
