#!/usr/bin/env node
/**
 * Verify an ML-DSA-87 signature generated by pq-crystals reference using qrypto.js.
 * Reads: /tmp/ref_mldsa87_pk.bin, /tmp/ref_mldsa87_sig.bin, /tmp/ref_mldsa87_msg.bin, /tmp/ref_mldsa87_ctx.bin
 */

import { readFileSync } from 'fs';
import { cryptoSignVerify } from '../../packages/mldsa87/src/sign.js';

console.log('=== qrypto.js ML-DSA-87 Verification (pq-crystals signature) ===');

// Read pq-crystals generated files
const pk = readFileSync('/tmp/ref_mldsa87_pk.bin');
const sig = readFileSync('/tmp/ref_mldsa87_sig.bin');
const msg = readFileSync('/tmp/ref_mldsa87_msg.bin');
const ctx = readFileSync('/tmp/ref_mldsa87_ctx.bin');

console.log(`Public key size: ${pk.length} bytes`);
console.log(`Signature size: ${sig.length} bytes`);
console.log(`Message size: ${msg.length} bytes`);
console.log(`Context size: ${ctx.length} bytes`);
console.log(`Message: "${msg.toString('utf8')}"`);
console.log(`Context: "${ctx.toString('utf8')}"`);
console.log(`Public key (first 32 bytes): ${pk.slice(0, 32).toString('hex')}`);
console.log(`Signature (first 32 bytes): ${sig.slice(0, 32).toString('hex')}`);

// Verify signature with context
const valid = cryptoSignVerify(sig, msg, pk, ctx);

if (valid) {
  console.log('\n✓ Signature verification PASSED');
  process.exit(0);
} else {
  console.error('\n✗ Signature verification FAILED');
  process.exit(1);
}
