#!/usr/bin/env node
/**
 * Verify an ML-DSA-87 signature generated by go-qrllib using qrypto.js.
 * Reads: $TMPDIR/qrypto_cross_verify/goqrllib_mldsa87_{pk,sig,msg,ctx}.bin
 */

import { readFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { cryptoSignVerify } from '../../packages/mldsa87/src/sign.js';

console.log('=== qrypto.js ML-DSA-87 Signature Verification ===');

// Read go-qrllib generated files from secure temp directory
const outputDir = join(tmpdir(), 'qrypto_cross_verify');
const pk = readFileSync(join(outputDir, 'goqrllib_mldsa87_pk.bin'));
const sig = readFileSync(join(outputDir, 'goqrllib_mldsa87_sig.bin'));
const msg = readFileSync(join(outputDir, 'goqrllib_mldsa87_msg.bin'));
const ctx = readFileSync(join(outputDir, 'goqrllib_mldsa87_ctx.bin'));

console.log(`Public key size: ${pk.length} bytes`);
console.log(`Signature size: ${sig.length} bytes`);
console.log(`Message size: ${msg.length} bytes`);
console.log(`Context size: ${ctx.length} bytes`);
console.log(`Message: "${msg.toString('utf8')}"`);
console.log(`Context: "${ctx.toString('utf8')}"`);
console.log(`Public key (first 32 bytes): ${pk.slice(0, 32).toString('hex')}`);
console.log(`Signature (first 32 bytes): ${sig.slice(0, 32).toString('hex')}`);

// Verify signature with context
const valid = cryptoSignVerify(sig, msg, pk, ctx);

if (valid) {
  console.log('\n✓ Signature verification PASSED');
  process.exit(0);
} else {
  console.error('\n✗ Signature verification FAILED');
  process.exit(1);
}
